/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.19).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package it.cnr.iasi.saks.groucho.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-06-13T15:56:16.649+02:00[Europe/Berlin]")
@Api(value = "reset", description = "the reset API")
public interface ResetApi {

    @ApiOperation(value = "Suggest to Restore the State of the Obeserver to the Default Configurations.", nickname = "resetStateObserver", notes = "Suggest to Restore the State of the Obeserver to the Default Configurations. It is only a suggestion, there is no commitment from the reciver.", response = Object.class, tags={ "resetStateObserver", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful Operation.", response = Object.class),
        @ApiResponse(code = 400, message = "Reset Not Allowed."),
        @ApiResponse(code = 404, message = "Reset Exception.") })
    @RequestMapping(value = "/reset",
        produces = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<Object> resetStateObserver();

}
